# Set prefix for bash commands
PS1="\W/ "

# Set CLICOLOR if you want Ansi Colors in iTerm2
export CLICOLOR=1

# Set colors to match iTerm2 Terminal Colors
export TERM=xterm-256color

export LSCOLORS=GxFxCxDxBxegedabagaced
