" use vim not vi
set nocompatible

" Keybindings to jk 
:imap jk <Esc>
set timeoutlen=150

" Relative line numbers
set relativenumber
set number

" Allow line-breaking and word wrapping
set wrap
set linebreak

" Autoformats display line to new line
set fo=tcrwa textwidth=80

" Allow mouse control
set mouse=a

" Search down into subfolders
" Provides tab-completion for all file-related tasks
set path+=**

" Display all matching files when we tab complete
set wildmenu

" Allow hjkl movement through wrapped lines
noremap <buffer> <silent> k gk
noremap <buffer> <silent> j gj
noremap <buffer> <silent> 0 g0
noremap <buffer> <silent> $ g$

" Map CTRL+N to NERDTree
map <F5> :NERDTreeToggle<CR>

" Autoclose NERDTree if it is last open window
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

syntax on
filetype plugin on
set background=light
set ls=2            	" always show status line
set hlsearch        	" highlight searches
set incsearch       	" do incremental searching
set ruler           	" show the cursor position all the time
set visualbell t_vb=  " turn off error beep/flash
set ignorecase        " ignore case while searching
set ts=2							" set the tabs to two spaces
set expandtab
set shiftwidth=2
set tabstop=2
set backspace=indent,eol,start
set completeopt=longest,menu,preview
set autoindent
set scrolloff=5               " keep at least x lines above/below
set sidescrolloff=5           " keep at least x lines left/right
set hidden                    " this will go along"
set encoding=utf-8

" Set Enter to exit search highlighting
nnoremap <silent> <CR> :nohlsearch<CR>

" let mapleader = ","           " Remap leader to comma"
let base16colorspace=256
 
execute pathogen#infect()
call pathogen#helptags()
